# Generated by Django 3.2.4 on 2021-06-27 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='در اینجا نام کاربری خود را وارد نمایید', max_length=190, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(help_text='ایمیل خود را وارد نمایید', max_length=200, unique=True, verbose_name='ایمیل')),
                ('birth_date', models.DateField(blank=True, help_text='تاریخ تولد خود را وارد نمایید', null=True, verbose_name='تاریخ تولد')),
                ('age', models.IntegerField(blank=True, help_text='سن خود را وارد نمایید', null=True, verbose_name='سن')),
                ('bio', models.TextField(blank=True, help_text='درباره خود میتوانید چند خط بنویسید', null=True, verbose_name='درباره')),
                ('user_type', models.CharField(choices=[('df', 'کاربر عادی'), ('pr', 'کاربر حرفه ای'), ('te', 'معلم'), ('ad', 'ادمین')], max_length=2, verbose_name='نوع حساب')),
                ('favorite_tags', models.CharField(blank=True, max_length=100, null=True, verbose_name='تگ های مورد علاقه')),
                ('wallet_stock', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='موجودی کیف پول')),
                ('profile_image', models.ImageField(blank=True, default='profile_image/default.png', help_text='عکس پروفایل خود را وارد نمایید', upload_to='profile_image/%Y/%m/%d', verbose_name='عکس پروفایل')),
                ('is_premium', models.BooleanField(default=False, verbose_name='آیا کاربر ویژه هستید؟')),
                ('premium_until', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تا چه زمانی کاربر ویژه هستید')),
                ('user_level', models.IntegerField(blank=True, default=0, verbose_name='سطح حساب شما')),
                ('experiments', models.BigIntegerField(blank=True, default=15, verbose_name='میزان تجربه کاربری')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('courses_bought', models.ManyToManyField(related_name='cuser', to='courses.Course', verbose_name='دوره های خریداری شده')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب های کاربری',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_username_index'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='check_username_and_email'),
        ),
    ]
